### ISSUE TITLE
What's the best way to use a custom domain with GitHub Pages?

### ISSUE THREAD

**Issue by Androz2091** [andstor/jsdoc-action#24]
Hello,
I'm using your action for my repository. Here is my current workflow:
```yml
name: GitHub pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./src
          output_dir: ./docs
          config_file: .jsdoc.json
          template_name: Androz2091/minami
          front_page: README.md

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./docs
```
So as you can see, I'm building the docs with your action, and then deploying them with actions-gh-pages. The problem is that GitHub Pages doesn't use my custom domain name (if I add a CNAME to the gh-pages branch, it's overwritten each time). So, what is the best way to support a custom domain? Committing the CNAME file to my master branch and (I couldn't find how) tell to jsdoc to keep this file in the output directory? Or adding an option "cname: custom-domain.com" to your action, so your script adds a CNAME file with the domain name?
I don't know, if you could give me more information and what you think, thank you.
