### ISSUE TITLE
Error: Cannot find module 'escape-string-regexp'

### ISSUE THREAD

**Issue by samageloff** [andstor/jsdoc-action#39]
Hi @andstor -- thanks much for the plugin! Wondering if you might be able to take a look at this config/error? 

```
name: JSDoc

on: [pull_request]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: andstor/jsdoc-action@v1.0.2
        with:
          source_dir: ./src/modules
          output_dir: ./out
          template: minami
          front_page: README.md

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./out
```

```
📝 Generating documentation
/usr/local/bin/node /home/runner/work/_actions/andstor/jsdoc-action/v1.0.2/node_modules/jsdoc/jsdoc.js /home/runner/work/iron/iron/src/modules -r -R /home/runner/work/iron/iron/README.md -d /home/runner/work/iron/iron/out
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'escape-string-regexp'
Require stack:
- /home/runner/work/_actions/andstor/jsdoc-action/v1.0.2/node_modules/jsdoc/lib/jsdoc/name.js
- /home/runner/work/_actions/andstor/jsdoc-action/v1.0.2/node_modules/jsdoc/lib/jsdoc/app.js
- /home/runner/work/_actions/andstor/jsdoc-action/v1.0.2/node_modules/jsdoc/jsdoc.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Requizzle.requizzle (/home/runner/work/_actions/andstor/jsdoc-action/v1.0.2/node_modules/requizzle/lib/requizzle.js:84:29)
    at infectProxy (/home/runner/work/_actions/andstor/jsdoc-action/v1.0.2/node_modules/requizzle/lib/loader.js:79:31)
    at Module.targetModule.require (/home/runner/work/_actions/andstor/jsdoc-action/v1.0.2/node_modules/requizzle/lib/loader.js:97:44)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/runner/work/_actions/andstor/jsdoc-action/v1.0.2/node_modules/jsdoc/lib/jsdoc/name.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Object.load (/home/runner/work/_actions/andstor/jsdoc-action/v1.0.2/node_modules/requizzle/lib/loader.js:105:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/andstor/jsdoc-action/v1.0.2/node_modules/jsdoc/lib/jsdoc/name.js',
    '/home/runner/work/_actions/andstor/jsdoc-action/v1.0.2/node_modules/jsdoc/lib/jsdoc/app.js',
    '/home/runner/work/_actions/andstor/jsdoc-action/v1.0.2/node_modules/jsdoc/jsdoc.js'
  ]
}
Error: The process '/usr/local/bin/node' failed with exit code 1
```

**Comment by andstor** [comment]
Hi @samageloff 👋 

The workflow file looks good. However, there was a bug in the build system for [v1.0.2](https://github.com/andstor/jsdoc-action/releases/tag/v1.0.2). By using a newer version of this action, the build should succeed 👌

Just change `andstor/jsdoc-action@v1.0.2` to `andstor/jsdoc-action@v1` to use the latest major version.

**Comment by samageloff** [comment]
Hi @andstor, (sorry for the delete/double post):

I've updated to the recommended version and am now receiving this error:

```
Run andstor/jsdoc-action@v1
Installing JSDoc template: minami
/opt/hostedtoolcache/node/16.4.2/x64/bin/npm install minami --production --parseable
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 

added 1 package, and audited 29 packages in 14s

4 vulnerabilities (1 low, 3 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
Error: ENOENT: no such file or directory, open '/home/runner/work/_actions/andstor/jsdoc-action/v1/details./package.json'
```

Any thoughts on this one?

**Comment by andstor** [comment]
Hi @samageloff,
it seems that you are using Node v16.4.2. I guess you are using a self-hosted runner?

This action built using GitHub's standard Node version that comes with the `ubuntu-latest` virtual environment ([Ubuntu 20.04.3 LTS](https://github.com/actions/virtual-environments/blob/881dbcfda3a2eff38c549590d15344454109545a/images/linux/Ubuntu2004-README.md)). As of now, it is using Node v14.18.1. Using other versions of Node may therefore result in a broken build. By manually specifying the version of node, it should work. Just add the following workflow step before the build step.

```
- name: Setup node
  uses: actions/setup-node@v1
  with:
    node-version: 14.18.1
```
