### ISSUE TITLE
Unable to find the source file or directory /home/runner/work/_actions/andstor/jsdoc-action/v1/app/js

### ISSUE THREAD

**Issue by yafp** [andstor/jsdoc-action#8]
My action file looks as follows, based on your example for github pages:

```
name: GitHub pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./app
          output_dir: ./docs/test
          config_file: jsdoc.json
          template_name: docdash
          front_page: README.md

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./docs/test

```

If executed it fails in the Build section, see the following log:

```
Run andstor/jsdoc-action@v1
  with:
    source_dir: ./app
    output_dir: ./docs/test
    config_file: jsdoc.json
    template_name: docdash
    front_page: README.md
    recurse: true
Installing JSDoc template: docdash
/usr/local/bin/npm install docdash --production
+ docdash@1.2.0
added 3 packages from 3 contributors and audited 882321 packages in 7.954s
found 0 vulnerabilities

📝 Generating documentation
/usr/local/bin/node /home/runner/work/_actions/andstor/jsdoc-action/v1/node_modules/jsdoc/jsdoc.js /home/runner/work/media-dupes/media-dupes/app -r -c /home/runner/work/media-dupes/media-dupes/jsdoc.json -t node_modules/docdash -R /home/runner/work/media-dupes/media-dupes/README.md -d /home/runner/work/media-dupes/media-dupes/docs/test
ERROR: Unable to find the source file or directory /home/runner/work/_actions/andstor/jsdoc-action/v1/app/js
ERROR: Unable to find the source file or directory /home/runner/work/_actions/andstor/jsdoc-action/v1/main.js
Parsing /home/runner/work/media-dupes/media-dupes/app/js/modules/crashReporter.js ...
Parsing /home/runner/work/media-dupes/media-dupes/app/js/modules/ffmpeg.js ...
Parsing /home/runner/work/media-dupes/media-dupes/app/js/modules/githubUrls.js ...
Parsing /home/runner/work/media-dupes/media-dupes/app/js/modules/sentry.js ...
Parsing /home/runner/work/media-dupes/media-dupes/app/js/modules/settings.js ...
Parsing /home/runner/work/media-dupes/media-dupes/app/js/modules/ui.js ...
Parsing /home/runner/work/media-dupes/media-dupes/app/js/modules/unhandled.js ...
Parsing /home/runner/work/media-dupes/media-dupes/app/js/modules/utils.js ...
Parsing /home/runner/work/media-dupes/media-dupes/app/js/modules/youtubeDl.js ...
Parsing /home/runner/work/media-dupes/media-dupes/app/js/renderer.js ...
Generating output files...
Finished running in 0.99 seconds.
##[error]The process '/usr/local/bin/node' failed with exit code 1
```

Any idea about this issue? Is that an error from me?
