### ISSUE TITLE
Output rendering markdown wrong.

### ISSUE THREAD

**Issue by NotTimTam** [andstor/jsdoc-action#88]
Here is my github action configuration:
```yaml
name: Build and Deploy Documentation

on:
    push:
        branches:
            - main
            - dev

permissions:
    contents: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Build
              uses: andstor/jsdoc-action@v1
              with:
                  source_dir: ./
                  output_dir: ./docs
                  recurse: true
                  template: minami
                  front_page: README.md

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.REPO_TOKEN }}
                  publish_dir: ./docs

```

The output body shows plaintext separated by "�":
`�c�o�n�f�i�g�u�r�a�t�i�o�n�.� � �`

My readme.md is a standard, valid syntax markdown file.
